Add BinaryOperatorTransformationsTest
Given LexicalPreservingPrinter set,
BinaryExpr.Operator transformation fails

```
in com.github.javaparser.printer.lexicalpreservation.transformations.ast.body.BinaryOperatorTransformationsTest
instanceToStatic(com.github.javaparser.printer.lexicalpreservation.transformations.ast.body.BinaryOperatorTransformationsTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.RuntimeException: Attribute 'operator' does not corresponding to any expected value. Text: AND
	at com.github.javaparser.printer.lexicalpreservation.transformations.ast.body.BinaryOperatorTransformationsTest.instanceToStatic(BinaryOperatorTransformationsTest.java:39)
Caused by: java.lang.NoSuchFieldException: AND
	at com.github.javaparser.printer.lexicalpreservation.transformations.ast.body.BinaryOperatorTransformationsTest.instanceToStatic(BinaryOperatorTransformationsTest.java:39)

```